version: '3'

services:

  unity_cache:
    build: ./cacheserver
    container_name: unity_cache_server
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
      - ./data:/opt/cache
    ports:
      - "8126:8126"